#
# start swarm-registrator
# start consul template
# start haproxy
#
version: '2'

services:
  swarmregistrator:
    image: gliderlabs/registrator
    networks:
      - apps 
    environment:
      - constraint:node==ktr-omega
      - DOCKER_HOST=tcp://192.168.8.50:2378
    command: -internal -ttl 15 -ttl-refresh 5 consul://192.168.8.50:8500

  consultemplate:
    image: kuzzleio/consul-template
    depends_on:
      - haproxy
    volumes:
      - $PWD/docker:/usr/local/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/haproxy/:/haproxy/
    environment:
      - constraint:node==ktr-omega
      - DOCKER_HOST=tcp://192.168.8.50:2378
    command: -consul 192.168.8.50:8500 -template "/haproxy/haproxy.ctmpl:/haproxy/haproxy.cfg:docker exec lb_haproxy_1 /haproxy-start reload"

  haproxy:
    image: haproxy
    networks:
      - apps
#      - outside  
    environment: 
      - constraint:node==ktr-omega
    ports:
      - 0.0.0.0:88:80
      - 0.0.0.0:4443:443
    volumes:
      - $PWD/haproxy/:/usr/local/etc/haproxy/

  demowebserver:
    build:
      context: $PWD/demowebserver
    networks:
      - apps

networks:
  apps:
    driver: overlay
